### ISSUE TITLE
How do I use this effect for  buttons on my website?

### ISSUE THREAD

**Issue by albert-massey** [codrops/ParticleEffectsButtons#11]
I tried manipulating this code but I could only make it work if it was in it's own index.html and unaltered. It stops working even if I remove all the buttons but one. Can you please guide me on how to use it on my website? I really like it.

**Comment by lmgonzalves** [comment]
Please read the documentation:
https://github.com/codrops/ParticleEffectsButtons

**Comment by Tashows** [comment]
This seems weird to me as well. Even after reading the documentation (Basic usage) and including the files in the right manner, I keep getting `Uncaught TypeError: Cannot read property 'style' of null`, without even calling anything. Seems a bit of a rough start.

**Comment by Tashows** [comment]
Realized I had to include the file after the body element. Should add a note about that in the documentation.

**Comment by Tashows** [comment]
Realized I had to include the file after the body element. Would be nice to add a note about that in the documentation.

**Comment by lmgonzalves** [comment]
Just add a small note about it.
Thanks!
