### ISSUE TITLE
React Version 👋

### ISSUE THREAD

**Issue by transitive-bullshit** [codrops/ParticleEffectsButtons#2]
Hey guys,

I really liked this effect, so I ported it to React: [react-particle-effect-button](https://github.com/transitive-bullshit/react-particle-effect-button).

I tried to make it clear that it was a port and included links to the original article / author / source, but please let me know if you'd like me to include any additional disclaimers or legal info.

Let me know what you think and if it'd be cool to add a link to the react version in the readme.

Thanks!

**Comment by juandc** [comment]
Also waiting for the glory :raised_hands: :pray:

**Comment by intermundos** [comment]
Thanks for react version. Will try it right now and share results.

**Comment by lmgonzalves** [comment]
Thank you very much!
It's in the README.
