### ISSUE TITLE
Transparent lines on canvas

### ISSUE THREAD

**Issue by wsjscss** [codrops/ParticleEffectsButtons#7]
I found some lag on canvas when it is drawn. It ads transparent lines. Here is screenshots:

![2018-07-16 14 51 19](https://user-images.githubusercontent.com/20801385/42757345-55678786-8908-11e8-9dd0-f8f0131ce2ae.jpg)
![2018-07-16 14 54 44](https://user-images.githubusercontent.com/20801385/42757347-589ce694-8908-11e8-92c2-49a6d4ffbeff.jpg)

Tested in chrome browser on different machines.
Chrome: 67.0.3396.99
Chrome canary: 69.0.3493.0 (same effect)

Other browsers: Safari, Firefox - everything okay.

**Comment by lmgonzalves** [comment]
Thanks for reporting this!, and please sorry the delay...

I've been testing some things to solve it, and seems to be it works properly adding `will-change: transform` to `.particles-wrapper` and `.particles-button` elements.

I've updated the repo, so you can test it.
