### ISSUE TITLE
complete can not use?

### ISSUE THREAD

**Issue by kangaroo711** [codrops/ParticleEffectsButtons#8]
> const arrOpts = [
    {
      type: "triangle",
      style: "stroke",
      direction: "top",
      size: 5,
      color: "red",
      duration: 1400,
      speed: 1.5,
      oscillationCoefficient: 15,
      direction: "left",
      begin: function(e) {
        console.log(e);
        // translate();
      },
      complete: function(e) {
        console.log(e);
        // translate(); 
      }
    }
  ];

the begin can use ,but the complete can't;

**Comment by lmgonzalves** [comment]
The `complete` option works properly.
If you are testing it in the demo, you need to take into account this piece of code, that is setting (overriding) the `complete` option for every button:

```js
particlesOpts.complete = () => {
  // CODE
};
```

Hope it helps!
