### ISSUE TITLE
Page Redirection

### ISSUE THREAD

**Issue by jessicalily** [codrops/ParticleEffectsButtons#9]
Hello! Loved this project, just a small query..

I'm using these buttons for my hybrid app to link them to other pages.. How can we first show the entire button burst effect and then take them to the desired location? Is there any way?

_Thank you so much!_

**Comment by lmgonzalves** [comment]
Yes it's possible to do that.
You need to do the following:

- Prevent the link with JavaScript.
- Create a function to change window location, and add it as the `complete` option in the `Particles` constructor. Please read more about `Particles` options in the project documentation.

Cheers
